//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbContextsEntities : DbContext
    {
        public DbContextsEntities()
            : base("name=DbContextsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<loaisanpham> loaisanphams { get; set; }
        public virtual DbSet<nhomsanpham> nhomsanphams { get; set; }
        public virtual DbSet<phieugiaohang> phieugiaohangs { get; set; }
        public virtual DbSet<phieunhap> phieunhaps { get; set; }
        public virtual DbSet<phuongthucthanhtoan> phuongthucthanhtoans { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<thuonghieu> thuonghieux { get; set; }
        public virtual DbSet<xuatkho> xuatkhoes { get; set; }
    
        public virtual ObjectResult<Sp_ReportSanPham_Result> Sp_ReportSanPham()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ReportSanPham_Result>("Sp_ReportSanPham");
        }
    }
}
