//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        public string id_sanpham { get; set; }
        public string tensanpham { get; set; }
        public string id_loai { get; set; }
        public decimal gia { get; set; }
        public int id_thuonghieu { get; set; }
        public int baohanh { get; set; }
        public int khuyenmai { get; set; }
        public string hinh { get; set; }
        public int soluong { get; set; }
        public string mota { get; set; }
        public System.DateTime ngaytao { get; set; }
        public System.DateTime ngaycapnhat { get; set; }
    }
}
